Only prevent default zooming when holding ctrl key.
enso-org/ide pull request #1001
Opened 2020-11-26 14:16 UTC by MichaelMauderer

### Pull Request Description
This changes the event handling behaviour when using the mouse wheel. Right now we prevent all default events, but this prevents also some [html components from receiving events](https://github.com/enso-org/ide/issues/939). Allowing default events while zooming with CTRL key, will lead to bad behaviour: the browser will do its website zooming and our UI will also zoom. We want to avoid the website zooming, but we do want to allow panning events to be received by scrollable html components.
To achieve this, this PR allows default events when a mouse wheel event is a pan event, but keeps it deactivated when there is a zoom event on CTRL + mouse wheel. 

### Checklist
Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/luna/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2020-11-27 09:12 UTC, farmaazon reviewed
I did some testing, and found two undesired things:
1. Scrolling visualization works properly if it is active - vis scrolls, and nothing else. However, when visualization is not active, both vis and application are scrolling
2. Documentation panel scrolls with application even when it is active (I clicked into it).

It's supposed to work properly, because the event should have prevented default always when it's propagation is stopped (that is: always, except the visualization is active). And documentation should behave as a normal visualization.

Could you investigate it a little before merging?

2020-11-27 15:06 UTC, MichaelMauderer commented
@farmaazon 
> Scrolling visualization works properly if it is active - vis scrolls, and nothing else. However, when visualization is not active, both vis and application are scrolling

Can you show a video of that? I can't seem to reproduce this on my system.

> Documentation panel scrolls with application even when it is active (I clicked into it).

I think documentation was never given an "active" state so far. So clicking there does not deactivate navigator.
 I'll have a look at correcting that.

2020-11-27 15:25 UTC, farmaazon commented
> > Scrolling visualization works properly if it is active - vis scrolls, and nothing else. However, when visualization is not active, both vis and application are scrolling
> 
> Can you show a video of that? I can't seem to reproduce this on my system.
> 

[scrolling.zip](https://github.com/enso-org/ide/files/5608516/scrolling.zip)

This happens when I scroll with mouse over the visualization (without clicking on it).

2020-11-30 07:20 UTC, wdanilo approved these changes

2020-12-01 11:08 UTC, MichaelMauderer commented
@farmaazon This now also extends the searcher documentation panel to have "selected" status, that is passed through the controller to the graph editor to enable/disable the navigator.

2020-12-01 14:02 UTC, farmaazon requested changes

2020-12-01 14:02 UTC, farmaazon commented on src/rust/ide/src/view/integration.rs
> +
I think this is wrong place: this file is integration between controllers and view, but here we integrate two views: documentation and graph.

The proper place is src/rust/ide/view/src/project.rs: the view containing both documentation panel and graph.

2020-12-01 14:05 UTC, farmaazon commented
And I tested it: now I see table and documentation scrolling working properly, but scatter plot still "scrolls" with the scene when not active. However, as it is no regression introduced by this PR, so let's merge it and I'll create a proper bug report.

2020-12-02 11:23 UTC, farmaazon approved these changes

2020-12-02 11:25 UTC, merged