Enable the watch scrtipt to download and use the pre-built project manager.
enso-org/ide pull request #1104
Opened 2021-01-11 15:36 UTC by MichaelMauderer

### Pull Request Description
Adds functionality to download and start the project manager to the watch script.
Also add a command line toggle to enable/disable this behaviour.

### Checklist
Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2021-01-17 07:10 UTC, wdanilo approved these changes

2021-01-17 07:10 UTC, wdanilo commented on src/js/lib/client/src/preload.js
> +
The error should be more specific - instead fo "animation during preload" it should tell "window startup animation"

2021-01-17 07:10 UTC, wdanilo commented on src/js/lib/client/src/preload.js
> +    }
I dont think this is the respoinsibility of this function to check if the arg was correct. Instead, check it on the call side, please.

2021-01-17 07:11 UTC, wdanilo requested changes
Why these are not checked?
![image](https://user-images.githubusercontent.com/1623053/104833776-8f29f980-589b-11eb-890f-74bb5773f617.png)

2021-01-18 12:59 UTC, MichaelMauderer commented
> Why these are not checked?
> ![image](https://user-images.githubusercontent.com/1623053/104833776-8f29f980-589b-11eb-890f-74bb5773f617.png)

`debug/interface` is not applicable, and the other box has been done now.

2021-01-21 07:59 UTC, wdanilo approved these changes

2021-01-21 07:59 UTC, wdanilo commented on build/run.js
> +// platform.
use 3 `/` instead of 2

2021-01-21 13:52 UTC, merged