Making CI config more generic
enso-org/ide pull request #1158
Opened 2021-01-27 21:23 UTC by wdanilo

### Pull Request Description

### Important Notes

### Checklist
Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2021-01-29 08:49 UTC, farmaazon requested changes
* I like this JS code, it is very clear.
* Currently we don't make the release build on the feature branches, and thus we don't check the wasm binary size limit before merging to master (blocker)
* I think we also should check on feature branches if CHANGELOG file have a proper format.
* I would also add a new check to the PR template to make sure the CHANGELOG was updated if applicable.

2021-01-29 08:49 UTC, farmaazon commented on build/run.js
> +const { promisify } = require('util')
Can we sort those "imports" alphabetically?

2021-01-29 08:49 UTC, farmaazon commented on docs/CONTRIBUTING.md
> +
This does not tell the full story how the CHANGELOG file should look like: That each version is a single-`#` section with the necessary "Enso " prefix and the version as described.

Do I understand correctly, that once we do merge to stable branch we modify changelog to merge all alphas, betas and rcs into a single changelog for a new stable version?

2021-01-30 18:26 UTC, wdanilo commented
> * I like this JS code, it is very clear.
Thanks!

> * Currently we don't make the release build on the feature branches, and thus we don't check the wasm binary size limit before merging to master. We should do it on at least one platform (blocker).
Good point, done.

> * I think we also should check on feature branches if CHANGELOG file have a proper format.
We do it on every execution of the `./run` script to update our JS configs, so it's already done.

> * I would also add a new check to the PR template to make sure the CHANGELOG was updated if applicable.
Done!

2021-02-01 11:22 UTC, farmaazon approved these changes
Only minor comment - to consider, no need to be applied

2021-02-01 11:22 UTC, farmaazon commented on build/release.js
> +            throw `Improper changelog entry header: ${section}. It should start with`
Looks like something is missing.

2021-02-01 11:22 UTC, farmaazon commented on docs/README_TEMPLATE.md
> +...
This file is hilarious :D however I wonder if we need so long a template?

2021-02-02 05:07 UTC, merged