Update AST - new import syntax etc.
enso-org/ide pull request #1186
Opened 2021-02-09 11:29 UTC by BinarySoftware

### Pull Request Description

### Important Notes

### Checklist
Please include the following checklist in your PR:

- [ ] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2021-02-10 16:20 UTC, farmaazon approved these changes
Apply comments before merge.

2021-02-10 16:20 UTC, farmaazon commented on CHANGELOG.md
> +
I think this should not be written in changelog. It means nothing to the users.

2021-02-10 16:20 UTC, farmaazon commented on src/rust/ide/lib/parser/build.rs
> +const PARSER_COMMIT: &str = "5e309bddcbec33cfbd150fcb8a16b45192cf5189";
Remove the FIXME part of docs, as we don't use the backported branch AFAIK.

2021-02-10 16:20 UTC, farmaazon commented on src/rust/ide/lib/parser/tests/parsing.rs
> +}
add a newline

2021-02-10 16:56 UTC, BinarySoftware commented on CHANGELOG.md
> +
Well, something needs to be written, otherwise CI check will fail. Any suggestions?

2021-02-11 08:41 UTC, farmaazon commented on CHANGELOG.md
> +
Yes. Just add `[ci no changelog needed]` in the commit message (see https://github.com/enso-org/ide/actions/runs/555353080)

2021-02-12 01:51 UTC, mwu-tow requested changes

2021-02-12 01:51 UTC, mwu-tow commented on CHANGELOG.md
> +
spurious newline?

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/ast/impl/src/crumbs.rs
> +    Path {index:usize}
This should also cover other `T`-dependent fields introduced to `Import` shape.
Other new shapes should also get their crumb classes, most importantly `Annotate`.
Basically the intent was to keep all the shapes and crumbs structure compatible.

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/macros.rs
> +    expect_import("from Foo import all hiding Bar");
We should also try going for the trickiest (as in using all possible fields in a non-empty way) imports possible here.

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/parsing.rs
> +/// Fixed test case, where we used to get invalid suffix, instead of infix.
There's no need to document test as "fixed". I just document "unfixed" ones with FIXMEs.

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/parsing.rs
> +            if let Shape::Var(Var{..}) = rarg.shape() {
This does not look correct, I believe the shape in within `rarg` should be an `Opr`.
`+` is not a `Var` identifier.

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/parsing.rs
> +    if let Shape::Infix(Infix {larg:_larg,loff:_loff,opr,roff:_roff,rarg}, ..) = ast.shape() {
All the matched fields (here and below) should be asserted to contain sensible values.

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/macros.rs
> +    expect_import("from Foo import all hiding Bar");
We could just take examples from the docs.

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/macros.rs
>      expect_not_import("type Foo");
We should test that exports are not recognized as imports.

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/ast/impl/src/macros.rs
> +    keyword.contains_if(|str| *str == QUALIFIED_IMPORT_KEYWORD || *str == UNQUALIFIED_IMPORT_KEYWORD)
Won't that recognize the unqualified export as an unqualified import?
Consider: `from Base.Data.List export Cons, Nil, from_vector`

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/parsing.rs
>      fn deserialize_macro_matches(&mut self) {
Like we have these, we should also add a method that tests deserialization of the newly introduced `Annotation` shape. If it is not possible/feasible for some reason (tbh I have no idea what `Annotation` shape is), then it should be mentioned in the comment in the `run` function, along with other not separately covered types.

2021-02-12 01:51 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/parsing.rs
>      fn deserialize_macro_matches(&mut self) {
Also, `deserialize_macro_matches` should be expanded with examples of code using the newly supported features (import/exports with renames, and this Documented thingy)

2021-02-12 11:08 UTC, BinarySoftware commented on src/rust/ide/lib/parser/tests/parsing.rs
>      fn deserialize_macro_matches(&mut self) {
From call : parser will never ever return AST.Documented

2021-02-12 11:09 UTC, BinarySoftware commented on src/rust/ide/lib/parser/tests/parsing.rs
> +            if let Shape::Var(Var{..}) = rarg.shape() {
This will go back to bugs

2021-02-15 13:47 UTC, mwu-tow approved these changes

2021-02-15 13:47 UTC, mwu-tow commented on src/rust/ide/lib/parser/tests/parsing.rs
> +            let expected_var = Annotation {name:"@Tail_call".into()};
`expected_var` should be named rather like `expected_annotation`

2021-02-15 16:48 UTC, merged