Wip/mwu/no import for methods 1178
enso-org/ide pull request #1209
Opened 2021-02-17 09:47 UTC by mwu-tow

### Pull Request Description
TBD

ref #1178

### Important Notes

### Checklist
Please include the following checklist in your PR:

- [ ] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2021-02-17 15:14 UTC, farmaazon approved these changes

2021-02-18 12:00 UTC, wdanilo approved these changes

2021-02-18 12:00 UTC, wdanilo commented on CHANGELOG.md
> +  declarations when inserting method calls.
Could you describe the issue a little bit more using simpler words and maybe bigger description? The changelog is for users snd they should understand what it is about. Even "inserting method calls" is not really understandable fully, as in the GUI its not obvious to every user what that's mean.

I would go this way (written fast, contains errors, just a scratch description):
```
[Not adding unnecessary library imports][1209]. Fixed situation when IDE was adding unnecessary libraries imports when selecting hints from node searcher. This makes the generated textual code easier to read.
```

2021-02-18 15:02 UTC, farmaazon requested changes
Unfortunately, the reality is more complex than I expected. Actually there is scenario which works wrong with the current solution: press tab without any node selected, pick Table.new and press enter.

the new is a method, but it is a method of not imported module "Table". So actually we should skip importing only when we pick a method for this argument.

2021-02-18 15:10 UTC, kustosz commented
@farmaazon @mwu-tow there's one more problem! Even if you have the `this`, some methods are extension methods. For an example, `Json.to_table` is a method defined `Table`, even though `Json` comes from `Base`. So the rule for "import is not necessary" is:
1. The method being called comes from the same module as `this`. In this case, never import.
2. The method being called comes from a different module than `this`. Then import the method's module.

2021-02-18 15:31 UTC, farmaazon commented
As for point 2: in scope of this task is only checking if we literally have the same import (as we do with other suggestions).

2021-02-18 15:35 UTC, kustosz commented
@farmaazon sure, point 1 is the most important one, because it could lead you towards overoptimization – i.e. not importing extension methods, which would break programs (and not just make them ugly by too many imports)

2021-02-18 15:35 UTC, kustosz commented
I have not read this code btw. it's very possible you've already taken everything into account :P Just saw this discussion and randomly commented

2021-02-18 15:45 UTC, farmaazon commented
No, no, the point 1 in your comment is important (cc @mwu), and no, we don't handle it in our code.

2021-03-04 12:51 UTC, farmaazon reviewed
Please, update the branch so I could easily test it with all new changes.

2021-03-04 12:51 UTC, farmaazon commented on src/rust/ide/src/model/suggestion_database/entry.rs
> +    // TODO [mwu] Currently we have no means to recognize module extension methods.
Could you add an issue for TODOs here? And add a note, that module extension methods will be treated as non-module methods.

2021-03-04 12:51 UTC, farmaazon commented on src/rust/ide/src/model/suggestion_database/entry.rs
> +            imports.insert(self.module.clone());
I don't understand the comment.

2021-03-04 12:51 UTC, farmaazon commented on src/rust/ide/src/model/suggestion_database/entry.rs
> +        println!("{:?}",self);
println left.

2021-03-05 15:03 UTC, farmaazon approved these changes

2021-03-08 12:03 UTC, merged