Show visualization on output port hover.
enso-org/ide pull request #1363
Opened 2021-03-23 15:01 UTC by MichaelMauderer

### Pull Request Description
Introduces a quick preview for visualizations and errors. Hovering a node output will first show a tooltip with the type information and then after some time, will show the visualization of the node. The preview visualization will be located above other nodes, whereas the normal view, will be shown below nodes.  
Some notes: errors will show the preview visualization immediately. Nodes without type information will show the visualization immediately. 

### Checklist
Please include the following checklist in your PR:

- [ ] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2021-03-24 10:19 UTC, wdanilo approved these changes
Michael, it looks amazing. I would definitely change two behaviors:
1. `Nodes without type information will show the visualization immediately` - this should not be here. The thing is that we do not show vis preview immediately in order not to have blinking in GUI, so no type information should not affect our visuals.
2. The error should be shown not only on output port hover, but just on this node hover.

2021-03-24 10:19 UTC, wdanilo commented on CHANGELOG.md
> +  quick preview mode by pressing ctrl, which will show the preview visualization
this should be command on mac

2021-03-24 10:19 UTC, wdanilo commented on CHANGELOG.md
> +  immediately for all nodes.
I dont think thisis true - it will show the visualization immediately for the hovered node, not for all nodes, right?

2021-03-24 10:19 UTC, wdanilo commented on src/rust/ensogl/lib/core/src/animation/frp/animation/delayed.rs
> +            frp.source.on_end   <+ transition.value.map(|t| (t - 1.0).abs() < std::f32::EPSILON).on_true();
too long - please check all new lines in the codebase and check if they cross the 100chars boundary

2021-03-24 10:19 UTC, wdanilo commented on src/rust/ide/view/graph-editor/src/component/node.rs
> +        quick_preview_vis                    (bool),
spacing of `(bool)`

2021-03-24 10:19 UTC, wdanilo commented on src/rust/ide/view/graph-editor/src/component/node.rs
> +        let error_visualization = builtin_visualization::Error::new(scene.clone_ref());
why do we need to provide scene clone to `Error`? Also, I think our APIs should always allow passing references to clone-refable things and just do clonesinside, not to force users of the API to manually create clone refs on every call side (it is just API simpler to use).

2021-03-24 10:19 UTC, wdanilo commented on src/rust/ide/view/graph-editor/src/component/node.rs
> +                    return 0.0;
I'd be thankful if we do not use in the code early-return statements if not needed necessarily. The functional, dataflow program structure is more obvious to the reader.

2021-03-24 10:19 UTC, wdanilo commented on src/rust/ide/view/graph-editor/src/component/node.rs
> +                if *visible {
use `.asSome(...)`

2021-03-24 10:19 UTC, wdanilo commented on src/rust/ide/view/graph-editor/src/lib.rs
> +}
1. Very cool.
2. I'd name it `NewNodeData` or something likethat to indicate its purpose

2021-03-24 10:19 UTC, wdanilo commented on src/rust/ide/view/graph-editor/src/lib.rs
> +          , (Release     , ""              , "ctrl" , "disable_quick_visualization_preview")
this does not work good on mac! On mac, `ctrl` is used only in special situations,l like killing a process. Use `cd` instead (which maps to ctrl on linu and windows).

2021-03-24 20:33 UTC, wdanilo commented
Michael, could you please also move the popup below the mouse, like it is on main now? I was playing with main today and it looks so beautiful and consistent with the popup below the mouse, not on the right? If you could just make it configurable (I think it is), it would be cool, so we will play with both versions

2021-03-25 12:11 UTC, MichaelMauderer commented
> Michael, could you please also move the popup below the mouse, like it is on main now? I was playing with main today and it looks so beautiful and consistent with the popup below the mouse, not on the right? If you could just make it configurable (I think it is), it would be cool, so we will play with both versions

Done. This can be configured on a per-tooltip basis. (See last commit on this branch)

2021-03-25 16:17 UTC, mwu-tow requested changes
I've run the testing scenarios. Here are the issues I've written down:

# BASIC SCENARIO

1. When I press tab and start typing a new node (with no prior selection), the tooltip appear, despite not having content.
Tooltip should not appear while we are creating node.
Also, tooltip should never appear empty. It should either not appear in such cases or include some diagnostics, as to why it is empty.

2. Histogram visualization has broken panning. When I move mouse with MMB pressed, it quickly goes wild.

3. "Fit all" button in histogram stops working after too much panning is done.

4. Likewise, visualization zooming is broken when dragging with RMB pressed.

5. Engine reports execution failures: `Execution failed in context f8ff239e-dc10-4521-b96c-ec507a128412. Error: Methods cannot be overloaded, but you have tried to overload Histogram.enso_project.`.

6. It is impossible to enter the node with `func1` after adding a new defaulted parameter. (test scenario 1): error in console `Error while performing UI action on controllers: The suggestion with id 1567 has not been found in the database.` 

7. It is impossible to connect additional input to `func1` as there is no placeholder for it on node.

8. Due to above issues some testings steps have been omitted. Once issues are addressed, the full test scenario should be once more checked.



# TRAMS SCENARIO
1. The table visualization does not appear on `fields.get "vehicles"`. Can be triggerred though..

2. There is no such method as `Geo.points`. 

3. The geo map visualization not only does not open bubt it is impossible to be selected (missing from visualziations list).

4. Further steps of the scenario are too sketchy for me to follow. Will need to chat with @sylwiabr  later.



Some well known issues are omitted for clarity,

2021-03-26 08:44 UTC, farmaazon commented
> I've run the test scenarios. Here are the issues I've written down:
> 
> # BASIC SCENARIO
> 2. Histogram visualization has broken panning. When I move mouse with MMB pressed, it quickly goes wild.
> 3. "Fit all" button in histogram stops working after too much panning is done.

I spotted those two also on my branch, so those are likely regressions on develop.

> 6. It is impossible to enter the node with `func1` after adding a new defaulted parameter. (test scenario 1): error in console `Error while performing UI action on controllers: The suggestion with id 1567 has not been found in the database.`
> 7. It is impossible to connect additional input to `func1` as there is no placeholder for it on node.

Those are engine issues and were reported some time ago.

> # TRAMS SCENARIO
> 3. The geo map visualization not only does not open bubt it is impossible to be selected (missing from visualziations list).

This also was reported as a develop regression

2021-03-29 07:38 UTC, MichaelMauderer commented
>     1. When I press tab and start typing a new node (with no prior selection), the tooltip appear, despite not having content.
>        Tooltip should not appear while we are creating node.
>        Also, tooltip should never appear empty. It should either not appear in such cases or include some diagnostics, as to why it is empty.
This is somewhat fixed. The really proper solution would be to check whether the node has an output value from the engine, but that information is not currently available to the node. So now this only skips nodes that do not yet have content to avoid the pop-up on empty nodes.

>     2. Histogram visualization has broken panning. When I move mouse with MMB pressed, it quickly goes wild.

Regression unrelated to this PR.

>     3. "Fit all" button in histogram stops working after too much panning is done.

Regression unrelated to this PR.

>     4. Likewise, visualization zooming is broken when dragging with RMB pressed.


>     5. Engine reports execution failures: `Execution failed in context f8ff239e-dc10-4521-b96c-ec507a128412. Error: Methods cannot be overloaded, but you have tried to overload Histogram.enso_project.`.
> 
>     6. It is impossible to enter the node with `func1` after adding a new defaulted parameter. (test scenario 1): error in console `Error while performing UI action on controllers: The suggestion with id 1567 has not been found in the database.`
> 
>     7. It is impossible to connect additional input to `func1` as there is no placeholder for it on node.
> 
>     8. Due to above issues some testings steps have been omitted. Once issues are addressed, the full test scenario should be once more checked.
> 
> 
> # TRAMS SCENARIO
> 
>     1. The table visualization does not appear on `fields.get "vehicles"`. Can be triggerred though..
> 
>     2. There is no such method as `Geo.points`.
> 
>     3. The geo map visualization not only does not open bubt it is impossible to be selected (missing from visualziations list).
> 
>     4. Further steps of the scenario are too sketchy for me to follow. Will need to chat with @sylwiabr  later.
> 
> 
> Some well known issues are omitted for clarity,

2021-03-29 09:01 UTC, MichaelMauderer commented
> # TRAMS SCENARIO
> 
>     1. The table visualization does not appear on `fields.get "vehicles"`. Can be triggerred though..

Regression on develop. When opening the table vis on this node it opens up as empty for me.

>     2. There is no such method as `Geo.points`.

I believe there is only a `Geo.point` method. But I don't see either used in the Scenario. Can you point out where this happens?

2021-03-29 09:18 UTC, farmaazon commented
@MichaelMauderer 

> I believe there is only a `Geo.point` method. But I don't see either used in the Scenario. Can you point out where this happens?

Yes, it was fixed when me and Michał went through the scenario together recently.

2021-03-30 09:13 UTC, mwu-tow requested changes
@MichaelMauderer 
I did the following:
* start a new unnamed project
* move nodes
* save
* reopen IDE
* hover nodes

The first nodes has tooltip with type. The second node (sort) has no tooltip. Though it likely is caused by a factor external to this PR, as node output port is also missing colors. Still might be worth investigating, as this PR makes the issue more visible.

***

Observed this when I was about to perform the copying step of the scenario.

![obraz](https://user-images.githubusercontent.com/1548407/112963263-7d8c8a00-9147-11eb-9e9f-20b75e51bfca.png)

***

Visualization automatically appears when I try to add a node after File.read.


https://user-images.githubusercontent.com/1548407/112964968-1a9bf280-9149-11eb-99c9-4bc7bb7ab0dc.mp4



***

I haven't tested further, once those issues are resolved (or confirmed as known issues unrelated to the PR) I will retest.
Please also merge develop, it should bring at least some fixes.

2021-03-30 10:09 UTC, MichaelMauderer commented
> @MichaelMauderer
> I did the following:
> 
>     * start a new unnamed project
> 
>     * move nodes
> 
>     * save
> 
>     * reopen IDE
> 
>     * hover nodes
> 
> 
> The first nodes has tooltip with type. The second node (sort) has no tooltip. Though it likely is caused by a factor external to this PR, as node output port is also missing colors. Still might be worth investigating, as this PR makes the issue more visible.

This is expected behaviour, if the node has no type information (which would explain why it has no colour either). If there is no type information to display, no tooltip is shown. But otherwise this is a bug that should be reported as "Node that should have a type does not have a type".


> Observed this when I was about to perform the copying step of the scenario.
> 
> ![obraz](https://user-images.githubusercontent.com/1548407/112963263-7d8c8a00-9147-11eb-9e9f-20b75e51bfca.png)

I believe this has been addressed on Discord?

> Visualization automatically appears when I try to add a node after File.read.
> Enso.2021-03-30.11-06-55.mp4

It looks like you are still hovering another node, so this is expected behaviour unless we want to prevent hovering while editing a node. 

> I haven't tested further, once those issues are resolved (or confirmed as known issues unrelated to the PR) I will retest.
Please also merge develop, it should bring at least some fixes.

Branch is updated to newest develop.

2021-03-30 11:12 UTC, mwu-tow commented
@MichaelMauderer 
> It looks like you are still hovering another node, so this is expected behaviour unless we want to prevent hovering while editing a node.

To me it looks like bug, even if it was designed this way. User must hover node to click on it to select. Then they open searcher to create a new node. And after a moment a strange popup appears, obscuring everything. They should not be required to move mouse away from node before opening searcher. This looks to me like a very common scenario.

Also, observe behavior on the video closely. At the moment when visualization appears, the output port *is not hovered*. It was hovered for a brief moment before, however mouse was moved and the type tooltip was hidden.

2021-03-30 13:11 UTC, MichaelMauderer commented
> > It looks like you are still hovering another node, so this is expected behaviour unless we want to prevent hovering while editing a node.
> 
> To me it looks like bug, even if it was designed this way. User must hover node to click on it to select. Then they open searcher to create a new node. And after a moment a strange popup appears, obscuring everything. They should not be required to move mouse away from node before opening searcher. This looks to me like a very common scenario.
> 
> Also, observe behavior on the video closely. At the moment when visualization appears, the output port _is not hovered_. It was hovered for a brief moment before, however mouse was moved and the type tooltip was hidden.

@mwu-tow You are right! It seems the FRP endpoint I hooked into was not only triggered when hovering the output port but some additional area. This is fixed now.

2021-03-30 14:41 UTC, mwu-tow commented
The issue seems resolved to me.

2021-03-30 16:01 UTC, mwu-tow approved these changes

2021-03-30 18:51 UTC, merged