Implement Suggestions DB schema and get `documentation_html` from engine.
enso-org/ide pull request #1601
Opened 2021-06-04 11:30 UTC by BinarySoftware

### Pull Request Description
Removes need to run doc parser, as it already feeds suggestionDB with HTML docs.
Applies [engine's 1698](https://github.com/enso-org/enso/issues/1698).

### Important Notes
DO NOT merge until it is implemented on engine side.

### Checklist
Please include the following checklist in your PR:

- [ ] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2021-06-21 12:01 UTC, farmaazon requested changes

2021-06-21 12:01 UTC, farmaazon commented on CHANGELOG.md
> +[1791]: https://github.com/enso-org/ide/pull/1791
What is that? I don't see a reference to 1791 anywhere above.

2021-06-21 12:01 UTC, farmaazon commented on src/rust/ide/lib/enso-protocol/src/language_server/types.rs
> -
keep this newline.

2021-06-21 12:01 UTC, farmaazon commented on src/rust/ide/lib/enso-protocol/src/language_server/types.rs
> +        documentation_html : Option<String>,
Why we keep both fields? It should be explained in a comment. And consider just ignoring the obsolete field.

2021-06-21 12:01 UTC, farmaazon commented on src/rust/ide/lib/enso-protocol/src/language_server/types.rs
> +    pub documentation_html : Option<FieldUpdate<String>>,
As above.

2021-06-21 12:01 UTC, farmaazon commented on src/rust/ide/src/model/suggestion_database/entry.rs
> +    pub documentation_html : Option<String>,
Again the matter of two documentation fields should be explained.

2021-06-21 12:01 UTC, farmaazon commented on src/rust/ide/view/src/documentation.rs
> +            Ok( if output.is_empty() { PLACEHOLDER_STR.into() } else { output } )
I don't know why this code it there. Why we look for <html> instead of checking input type? Why we check `is_empty` twice?

2021-06-21 12:01 UTC, farmaazon commented on src/rust/ide/view/src/documentation.rs
> +        display_doc_html (String),
Please remove anything related to old documentation, if it isn't needed anymore.

2021-06-21 13:45 UTC, BinarySoftware commented on src/rust/ide/lib/enso-protocol/src/language_server/types.rs
> +        documentation_html : Option<String>,
as discussed in dm, because of how the spec looks like : https://github.com/enso-org/enso/blob/main/docs/runtime/searcher.md#suggestions-table

2021-06-21 14:01 UTC, farmaazon commented on src/rust/ide/lib/enso-protocol/src/language_server/types.rs
> +        documentation_html : Option<String>,
Hmm, however we should not rely on that specification, but on the protocol description [here](https://enso.org/docs/developer/enso/language-server/protocol-language-server.html#suggestionentry). I see there no documentation_html, so probably you need to update that document.

2021-06-21 14:01 UTC, farmaazon commented on src/rust/ide/src/model/suggestion_database/entry.rs
> +    pub documentation_html : Option<String>,
Bump. This file is not a protocol client, so here is no point of keeping two documentations. We can just ignore the old and use only new.

2021-06-22 12:12 UTC, BinarySoftware commented on src/rust/ide/lib/enso-protocol/src/language_server/types.rs
> +        documentation_html : Option<String>,
Updated.

2021-06-24 06:45 UTC, farmaazon approved these changes

2021-07-29 20:45 UTC, merged