Clipping
enso-org/ide pull request #1720
Opened 2021-07-22 05:22 UTC by wdanilo

### Pull Request Description

### Important Notes

### Checklist
Please include the following checklist in your PR:

- [ ] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2021-07-26 09:51 UTC, farmaazon requested changes

2021-07-26 09:51 UTC, farmaazon commented on src/rust/Cargo.toml
> +enso-shapely-macros = { path = '../../../rust-lib/src/shapely/macros' }
Revert

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/example/src/complex_shape_system.rs
> +    let scene = world.scene().clone_ref();
Commented code. I know it is an example, but so far there was a rule of keeping examples code clean unless explicitly stated in docs that example is under construction.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/object/class.rs
> +                let old_scene_layers = mem::replace(&mut *self.scene_layers.borrow_mut(),new_scene_layers.to_vec());
over 100

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/object/class.rs
> +    where F : Fn(&Host,&[WeakLayer],&[WeakLayer]) + 'static {
Update docs. From signature I don't know what is are the two layer lists.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/object/class.rs
> +    // }
Why that was commented?

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/render/passes/symbols.rs
> +        // }
Commented code.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/scene.rs
> +             ,tooltip,tooltip_text,cursor,root,mask}
I feel this looks inconsistently: first we have a list with each element in separate line, but then we have similar list keeping elements in the same line as far as possible.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/scene.rs
> +            for layer in &*self.layers.children() {
If we want to keep HardcodedLayers Deref to root Layer, then probably the field name should be changed. Looking at this line I don't know what are "children of layers".

Also, it looks strange that we do anything with exactly one layer of hierarchical layers. Shan't the camera be updated also in each ones, also in grand children? And if the change is propagated, why don't we just set_screen on root?

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/scene.rs
> +        for layer in &*self.layers.children() {
Same as above.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/symbol/gpu.rs
> +            }
What about
```suggestion
            for layer in old_layers.iter().filter_map(Weak::upgrade) {
                layer.remove_symbol(id)
            }
```
For me it looks a little bit better, but I'm ok with your version too.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/gui/component.rs
> +        // self.init_on_show();
Commented code.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/gui/component.rs
> +            DEBUG!(">>> init_on_scene_layer_changed");
Debug left.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/gui/component.rs
> +
Remove line.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/gui/component.rs
>      before_first_show   : Cell<bool>,
This field is no longer used.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/gui/component.rs
> +        DEBUG!("on_scene_layers_changed: {old_layers:?} {new_layers:?}");
Debug log.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/gui/component.rs
> +        DEBUG!("?? drop_from_all_scene_layers: {old_layers:?}");
Debug log.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/gui/component.rs
> +        DEBUG!("created {instance.symbol_id:?} {instance.instance_id:?}");
Debug logs.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/scene/layer.rs
> +    }
I would rename it to "new_with_cam", as this is not "conversion camera to layer".

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/scene/layer.rs
> +    pub fn add_global_elements_order_dependency
The docs does not explain difference between global and non-global order dependency.

2021-07-26 09:51 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/scene/layer.rs
> +    pub fn remove_global_elements_order_dependency
Same as above.

2021-07-27 03:59 UTC, wdanilo commented on src/rust/ensogl/lib/core/src/display/scene.rs
> +             ,tooltip,tooltip_text,cursor,root,mask}
I do not know what to do about it. This allows sorting layers easier, and previous implementation had just long expressions per line. Im not sure I want to change it. I might create macro for it but I'm not sure if its not an overkill here.

2021-07-27 04:45 UTC, wdanilo commented on src/rust/ensogl/lib/core/src/display/symbol/gpu.rs
> +            }
I like it a lot!

2021-07-27 04:47 UTC, wdanilo commented on src/rust/ensogl/lib/core/src/gui/component.rs
>      before_first_show   : Cell<bool>,
Oh well, good catch! thanks!

2021-07-27 04:48 UTC, wdanilo commented on src/rust/ensogl/lib/core/src/gui/component.rs
> +        DEBUG!("on_scene_layers_changed: {old_layers:?} {new_layers:?}");
Sorry, I forgot to push cleaned PR without these logs :(

2021-07-27 04:52 UTC, wdanilo commented on src/rust/ensogl/example/src/complex_shape_system.rs
> +    let scene = world.scene().clone_ref();
I promise to clean it up in the next PR (the Clipping 2/2).

2021-07-27 08:13 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/scene.rs
> +             ,tooltip,tooltip_text,cursor,root,mask}
Ok we can keep it as it is. Maybe a little comment of explanation (otherwise someone else could alter it).

2021-07-27 08:23 UTC, farmaazon approved these changes

2021-07-27 08:23 UTC, farmaazon commented on src/rust/ensogl/lib/core/src/display/scene/layer.rs
> +    parents                         : Rc<RefCell<Vec<Sublayers>>>,
I miss it on first review: I don't understand why parents are vector of sublayers? Could you add a comment here?

2021-07-28 02:32 UTC, merged