Override config parameters
enso-org/ide pull request #1796
Opened 2021-08-13 07:55 UTC by 4e6

### Pull Request Description

[ci no changelog needed]

Be able to override global config in the cloud.

### Important Notes

### Checklist
Please include the following checklist in your PR:

- [x] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [x] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [x] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://airtable.com/shr7KPRypRpanF7TO).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://airtable.com/shr7KPRypRpanF7TO).

2021-08-13 08:43 UTC, MichaelMauderer requested changes
These parameters should probably also be added to `src/rust/ide/lib/args/src/lib.rs`.

2021-08-13 14:32 UTC, 4e6 commented
@MichaelMauderer I updated TypeScript and Rust configs and added missing parameters to both of them. Now they should be in sync again

2021-08-16 09:08 UTC, MichaelMauderer approved these changes

2021-08-17 08:09 UTC, farmaazon approved these changes

2021-08-17 08:09 UTC, farmaazon commented on src/rust/ide/src/config.rs
> +                    let namespace       = args.namespace.clone().unwrap_or_else(|| "local".to_owned());
Please make this "local" a constant in src/rust/ide/src/constants.rs

2021-10-14 23:09 UTC, merged