Update build script to separate builds for different targets and engine versions.
enso-org/ide pull request #1814
Opened 2021-08-25 09:23 UTC by s9ferech

### Pull Request Description

This implements task #1132.

### Important Notes

### Checklist
Please include the following checklist in your PR:

- [ ] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://airtable.com/shr7KPRypRpanF7TO).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://airtable.com/shr7KPRypRpanF7TO).

2021-08-25 09:24 UTC, s9ferech commented
Should this update have an entry in the CHANGELOG?

2021-08-26 15:38 UTC, MichaelMauderer requested changes
I just did a code review without testing yet as I'm on a weak connection at the moment. It might be worth to let this PR build packages to check that CI will have a working full build.

2021-08-26 15:38 UTC, MichaelMauderer commented on build/paths.js
> +paths.dist.tmp            = path.join(paths.dist.root,'tmp')
I would suggest something more specific like `tmpEngines`

2021-08-26 15:38 UTC, MichaelMauderer commented on build/run.js
> +        // FIXME: Among other things, this will call the build script of the project-manager
Actually, since we won't fix it, let's just leave the comment without the "FIXME" prefix.

2021-08-26 15:38 UTC, MichaelMauderer commented on src/js/lib/project-manager/src/build.ts
> +    } catch {
If there is an exception here, should we at least log it?

2021-08-26 16:14 UTC, s9ferech commented on build/paths.js
> +paths.dist.tmp            = path.join(paths.dist.root,'tmp')
The engines are actually downloaded into a subdirectory of `tmp` that is named `project-manager`. Do you still thing that `tmp` should be renamed?

2021-08-26 16:33 UTC, s9ferech commented on src/js/lib/project-manager/src/build.ts
> +    } catch {
I will check which kind of error it is. If the file does not exist then this expected and no logging necessary. Otherwise, It will throw the error again.

2021-08-27 09:10 UTC, MichaelMauderer commented on build/paths.js
> +paths.dist.tmp            = path.join(paths.dist.root,'tmp')
No then this should be fine.

2021-08-30 11:57 UTC, merged