Map visualization
enso-org/ide pull request #779
Opened 2020-09-03 14:05 UTC by BinarySoftware

### Pull Request Description
closes #736 

### Important Notes

### Checklist
Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/luna/enso/blob/main/docs/style-guide/rust.md).
- [ ] All code has been tested where possible.
- [ ] All code has been profiled where possible.

2020-09-09 09:31 UTC, farmaazon reviewed
I would wait for @wdanilo view review as well.

2020-09-09 09:31 UTC, farmaazon commented on src/js/lib/content/src/index.html
> +            }
Could it be somehow added by loaded visualization itself, instead of embedding it into index.html?

2020-09-10 16:41 UTC, wdanilo requested changes
![image](https://user-images.githubusercontent.com/1623053/92765023-41553000-f395-11ea-9417-7ad2be357876.png)

2020-09-17 14:41 UTC, wdanilo approved these changes

2020-09-17 14:43 UTC, wdanilo commented
Please lets talk about 
![image](https://user-images.githubusercontent.com/1623053/93486754-d790d500-f904-11ea-9499-7168c6bdaa2e.png)
before merging

2020-09-22 10:46 UTC, farmaazon reviewed
Please add the examples for using maps as an issue comment (according to its description).

2020-09-22 11:22 UTC, BinarySoftware commented on src/js/lib/content/src/index.html
> +            worker-src  'self' blob:;
We've talked about that on the phone and agreed what to do, the correct config is already on main.

2020-09-22 11:23 UTC, BinarySoftware commented on src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/mapView.js
> +}
As far as i can tell it downloads and attaches the scripts already while launching the app, and there is only one script when i show/hide vis multiple times, so this is not the case.

2020-09-22 14:37 UTC, BinarySoftware commented
Here are the screens:
<img width="316" alt="Zrzut ekranu 2020-09-22 o 16 14 10" src="https://user-images.githubusercontent.com/26655166/93897003-e22ae000-fcf1-11ea-90ba-b23043b2e3f2.png">

<img width="247" alt="Zrzut ekranu 2020-09-22 o 16 11 18" src="https://user-images.githubusercontent.com/26655166/93896996-e0611c80-fcf1-11ea-9d88-99e499d53f20.png">
<img width="384" alt="Zrzut ekranu 2020-09-22 o 16 09 12" src="https://user-images.githubusercontent.com/26655166/93896982-dc34ff00-fcf1-11ea-867c-bdfd92f83b4f.png">

2020-09-23 12:54 UTC, merged