Fix zooming and alt-tabbing
enso-org/ide pull request #839
Opened 2020-10-08 08:37 UTC by farmaazon

### Pull Request Description
This PR provides a fix for zooming broken by some previous commit. Additionally it also fix "stick-key" problem when alt-tabbing from IDE.

### Checklist
Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Rust](https://github.com/luna/enso/blob/main/docs/style-guide/rust.md) style guide.
- [x] All code has been tested where possible.
- [x] All code has been profiled where possible.

2020-10-08 15:32 UTC, wdanilo requested changes
A blocker for me - this file should be ignored, shouldnt it? src/rust/ensogl/lib/msdf-sys/msdfgen_wasm.js

2020-10-08 15:32 UTC, wdanilo commented on src/rust/ensogl/lib/core/src/control/io/mouse.rs
> +    options.capture(true).passive(false);
could you add comments here what it realy does with a links to appropriate msdn docs? I watn to read about it and understand the reasoning behind this solution.

2020-10-08 17:14 UTC, farmaazon commented
Well, msdfgen_wasm.js won't be generated in that location anymore, so it's no need for ignoring it there.

2020-10-09 07:57 UTC, wdanilo approved these changes

2020-10-09 08:02 UTC, merged