Quicktake: Fix textual visualizations look.
enso-org/ide pull request #988
Opened 2020-11-24 23:20 UTC by BinarySoftware

### Pull Request Description
Fixes text-based visualizations so that they are consistent with IDE.
Closes #933 

<img width="395" alt="Zrzut ekranu 2020-11-25 o 00 00 57" src="https://user-images.githubusercontent.com/26655166/100162383-c55a8680-2eb3-11eb-985b-0be13af7d8a6.png">

<img width="281" alt="Zrzut ekranu 2020-11-25 o 00 10 31" src="https://user-images.githubusercontent.com/26655166/100162387-c68bb380-2eb3-11eb-883f-85d00037e1a9.png">

### Important Notes
It cant affect IDE or introduce any regression. just a stylistic change. Nothing to worry about.

### Checklist
Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/luna/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [ ] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

2020-11-25 02:37 UTC, wdanilo approved these changes
Looks good!

2020-11-25 02:37 UTC, wdanilo commented on src/rust/ide/view/graph-editor/src/builtin/visualization/native/raw_text.rs
> +        let x_mod = size.x - 5.0;
hardcoded literal. Please move it to constant with a good name.

2020-11-25 02:40 UTC, wdanilo requested changes
Actually, one thing to be fixed visually - the padding. It should be equal to text padding on nodes. Right now, the raw text visualization has a big top padding and small left one. They should be equal and equal to the padding of text inside of nodes. The same applies to other visualizations. Please also consider right padding - please show the visualization with a long text to see how bottom and right padding behaves.

2020-11-25 14:10 UTC, BinarySoftware commented
Better paddings:
<img width="344" alt="Zrzut ekranu 2020-11-25 o 15 08 33" src="https://user-images.githubusercontent.com/26655166/100238261-47889080-2f30-11eb-89e1-e95b65b005c4.png">

2020-11-26 12:35 UTC, BinarySoftware commented
After talk with @farmaazon we've agreed that fixing scrollbars is bigger task, and it can be done in a separate PR. As we understand, @wdanilo, You want scrollbars to look like in safari, that their track doesnt overlap the background, which is non-trivial to actually implement correctly ;) Current implementation saves the day by disabling text to go out of bounds, especially that the visualization background has rounded corners, and that it is not a parent div to the visualization, rather that visualization "sits" on top of it.

2020-11-26 13:11 UTC, wdanilo commented
<img width="347" alt="paddings" src="https://user-images.githubusercontent.com/1623053/100354941-32276b00-2ff1-11eb-8add-5f0c7da2b60d.png">

@BinarySoftware are you sure these paddings are correct? Please make a screenshot with a node containing `{` as the first character and leats measure it on the screenshot

2020-11-26 22:32 UTC, BinarySoftware commented
Ok, so nodes actually have different paddings themselves, while the text vis has equal ones. Actually by creating a one-letter node i feel that the text is slightly off to the right- on node that is.
<img width="344" alt="Zrzut ekranu 2020-11-26 o 23 23 39" src="https://user-images.githubusercontent.com/26655166/100395029-94a75800-303f-11eb-95c7-38326615401e.png">

2020-11-26 23:19 UTC, wdanilo approved these changes

2020-11-26 23:21 UTC, merged